config/routes.rb
Rails.application.routes.draw do
  root "articles#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Defines the root path route ("/")
  
  # get '/articles', to: 'articles#index' # no more need because siya ang root; redundant

  get '/articles/new' => 'articles#new', as: 'new_article' #mas modern yung arrow
  post '/articles' => 'articles#create', as: 'create_article'
  get '/articles/:id', to: 'articles#show', as: 'article'
  get '/articles/:id/edit' => 'articles#edit', as: 'edit_article'
  patch '/articles/:id' => 'articles#update'
  delete '/articles/:id' => 'articles#delete'
  # post '/articles' => 'articles#create', as: 'create_article'
  # get '/articles/:id' => 'articles#show', as: 'article'
  # get '/articles/:id/edit' => 'articles#edit', as: 'edit_article'
  # # put '/articles/:id' => 'articles#update'
  # patch '/articles/:id' => 'articles#update'
  # delete '/articles/:id' => 'articles#delete'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end
  
  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    
    if @article.save
      redirect_to articles_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end
  
  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to root_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def delete
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to root_path
  end

  private
  def article_params
    params.require(:article).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/edit.html.erb
<h2>Not to be confused with 'New' page</h2>

<%= form_with model: @article do |f| %>
  <p>
    <%= f.label :title %> <br/>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :body %> <br/>
    <%= f.text_field :body %>
  </p>

  <p>
    <%= f.submit%>
  </p>
<% end %>

app/views/articles/index.html.erb
<h1>Whatzz up</h1>

<p><%= @articles %></p>

<% @articles.each do |article| %>
  <span><strong><%= article.title %></strong></span> 
  <%= link_to "Edit Article", edit_article_path(article) %>
  <p>article.body: <%= article.body %><p>
  <p>article.id: <%= article.id %><p>
  <%= button_to "Obliterate!", article_path(article), method: :delete%>
  <br>
  <br>
<% end %>

app/views/articles/new.html.erb
<%= form_with scope: :article, url: create_article_path, local: true do |f| %>
  <p>
    <%= f.label :title %> <br/>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :body %> <br/>
    <%= f.text_field :body %>
  </p>

  <p>
    <%= f.submit%>
  </p>
<% end %>

app/views/articles/show.html.erb
<h2>You're in show boih </h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Artikulobago</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>